package com.k_int.utils.cql.criteria;

import org.hibernate.criterion.DetachedCriteria

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class CQLToCriteria {

  
  DetachedCriteria build(String query) {
    DetachedCriteria result = null;
    return result;
  }
}
