/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

import com.k_int.utils.cql.criteria.CQLToCriteria;

class CQLToCriteriaTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new CQLToCriteria()

        when:
        def result = lib.build('(title=test*) and (ext.selected = true) sortby title')

        then:
        result == null
    }
}
